//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioMetrixCore.LogPushService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogDataBLL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LogDataBLL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OfficeIdField;
        
        private int OfficeDeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpAddressField;
        
        private int EnrollNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerifyModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InOutModeField;
        
        private int dwYearField;
        
        private int dwMonthField;
        
        private int dwDayField;
        
        private int dwHourField;
        
        private int dwMinuteField;
        
        private int dwSecondField;
        
        private int WorkcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BioMetrixCore.LogPushService.LogDataBLL> LogDateListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OfficeId {
            get {
                return this.OfficeIdField;
            }
            set {
                if ((this.OfficeIdField.Equals(value) != true)) {
                    this.OfficeIdField = value;
                    this.RaisePropertyChanged("OfficeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int OfficeDeviceId {
            get {
                return this.OfficeDeviceIdField;
            }
            set {
                if ((this.OfficeDeviceIdField.Equals(value) != true)) {
                    this.OfficeDeviceIdField = value;
                    this.RaisePropertyChanged("OfficeDeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IpAddress {
            get {
                return this.IpAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IpAddressField, value) != true)) {
                    this.IpAddressField = value;
                    this.RaisePropertyChanged("IpAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int EnrollNumber {
            get {
                return this.EnrollNumberField;
            }
            set {
                if ((this.EnrollNumberField.Equals(value) != true)) {
                    this.EnrollNumberField = value;
                    this.RaisePropertyChanged("EnrollNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string VerifyMode {
            get {
                return this.VerifyModeField;
            }
            set {
                if ((object.ReferenceEquals(this.VerifyModeField, value) != true)) {
                    this.VerifyModeField = value;
                    this.RaisePropertyChanged("VerifyMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string InOutMode {
            get {
                return this.InOutModeField;
            }
            set {
                if ((object.ReferenceEquals(this.InOutModeField, value) != true)) {
                    this.InOutModeField = value;
                    this.RaisePropertyChanged("InOutMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int dwYear {
            get {
                return this.dwYearField;
            }
            set {
                if ((this.dwYearField.Equals(value) != true)) {
                    this.dwYearField = value;
                    this.RaisePropertyChanged("dwYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int dwMonth {
            get {
                return this.dwMonthField;
            }
            set {
                if ((this.dwMonthField.Equals(value) != true)) {
                    this.dwMonthField = value;
                    this.RaisePropertyChanged("dwMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int dwDay {
            get {
                return this.dwDayField;
            }
            set {
                if ((this.dwDayField.Equals(value) != true)) {
                    this.dwDayField = value;
                    this.RaisePropertyChanged("dwDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int dwHour {
            get {
                return this.dwHourField;
            }
            set {
                if ((this.dwHourField.Equals(value) != true)) {
                    this.dwHourField = value;
                    this.RaisePropertyChanged("dwHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int dwMinute {
            get {
                return this.dwMinuteField;
            }
            set {
                if ((this.dwMinuteField.Equals(value) != true)) {
                    this.dwMinuteField = value;
                    this.RaisePropertyChanged("dwMinute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int dwSecond {
            get {
                return this.dwSecondField;
            }
            set {
                if ((this.dwSecondField.Equals(value) != true)) {
                    this.dwSecondField = value;
                    this.RaisePropertyChanged("dwSecond");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int Workcode {
            get {
                return this.WorkcodeField;
            }
            set {
                if ((this.WorkcodeField.Equals(value) != true)) {
                    this.WorkcodeField = value;
                    this.RaisePropertyChanged("Workcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public System.Collections.Generic.List<BioMetrixCore.LogPushService.LogDataBLL> LogDateList {
            get {
                return this.LogDateListField;
            }
            set {
                if ((object.ReferenceEquals(this.LogDateListField, value) != true)) {
                    this.LogDateListField = value;
                    this.RaisePropertyChanged("LogDateList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MachineBLL", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MachineBLL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OfficeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeNameField;
        
        private int OfficeDeviceIdField;
        
        private int MachineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIpField;
        
        private int DeviceNoField;
        
        private int PortField;
        
        private int LicenseNoField;
        
        private System.DateTime LastImportDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BioMetrixCore.LogPushService.MachineBLL> MachineListField;
        
        private bool IsCheckedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OfficeId {
            get {
                return this.OfficeIdField;
            }
            set {
                if ((this.OfficeIdField.Equals(value) != true)) {
                    this.OfficeIdField = value;
                    this.RaisePropertyChanged("OfficeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OfficeName {
            get {
                return this.OfficeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeNameField, value) != true)) {
                    this.OfficeNameField = value;
                    this.RaisePropertyChanged("OfficeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int OfficeDeviceId {
            get {
                return this.OfficeDeviceIdField;
            }
            set {
                if ((this.OfficeDeviceIdField.Equals(value) != true)) {
                    this.OfficeDeviceIdField = value;
                    this.RaisePropertyChanged("OfficeDeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int MachineId {
            get {
                return this.MachineIdField;
            }
            set {
                if ((this.MachineIdField.Equals(value) != true)) {
                    this.MachineIdField = value;
                    this.RaisePropertyChanged("MachineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DeviceIp {
            get {
                return this.DeviceIpField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIpField, value) != true)) {
                    this.DeviceIpField = value;
                    this.RaisePropertyChanged("DeviceIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int DeviceNo {
            get {
                return this.DeviceNoField;
            }
            set {
                if ((this.DeviceNoField.Equals(value) != true)) {
                    this.DeviceNoField = value;
                    this.RaisePropertyChanged("DeviceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Port {
            get {
                return this.PortField;
            }
            set {
                if ((this.PortField.Equals(value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int LicenseNo {
            get {
                return this.LicenseNoField;
            }
            set {
                if ((this.LicenseNoField.Equals(value) != true)) {
                    this.LicenseNoField = value;
                    this.RaisePropertyChanged("LicenseNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime LastImportDate {
            get {
                return this.LastImportDateField;
            }
            set {
                if ((this.LastImportDateField.Equals(value) != true)) {
                    this.LastImportDateField = value;
                    this.RaisePropertyChanged("LastImportDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public System.Collections.Generic.List<BioMetrixCore.LogPushService.MachineBLL> MachineList {
            get {
                return this.MachineListField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineListField, value) != true)) {
                    this.MachineListField = value;
                    this.RaisePropertyChanged("MachineList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool IsChecked {
            get {
                return this.IsCheckedField;
            }
            set {
                if ((this.IsCheckedField.Equals(value) != true)) {
                    this.IsCheckedField = value;
                    this.RaisePropertyChanged("IsChecked");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogPushService.LogPushSoap")]
    public interface LogPushSoap {
        
        // CODEGEN: Generating message contract since element name devicedata from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PushLogRefrence", ReplyAction="*")]
        BioMetrixCore.LogPushService.PushLogRefrenceResponse PushLogRefrence(BioMetrixCore.LogPushService.PushLogRefrenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PushLogRefrence", ReplyAction="*")]
        System.Threading.Tasks.Task<BioMetrixCore.LogPushService.PushLogRefrenceResponse> PushLogRefrenceAsync(BioMetrixCore.LogPushService.PushLogRefrenceRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllMachineResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMachine", ReplyAction="*")]
        BioMetrixCore.LogPushService.GetAllMachineResponse GetAllMachine(BioMetrixCore.LogPushService.GetAllMachineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMachine", ReplyAction="*")]
        System.Threading.Tasks.Task<BioMetrixCore.LogPushService.GetAllMachineResponse> GetAllMachineAsync(BioMetrixCore.LogPushService.GetAllMachineRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushLogRefrenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushLogRefrence", Namespace="http://tempuri.org/", Order=0)]
        public BioMetrixCore.LogPushService.PushLogRefrenceRequestBody Body;
        
        public PushLogRefrenceRequest() {
        }
        
        public PushLogRefrenceRequest(BioMetrixCore.LogPushService.PushLogRefrenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PushLogRefrenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BioMetrixCore.LogPushService.LogDataBLL> devicedata;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeviceIp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime lastimportdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public BioMetrixCore.LogPushService.MachineBLL machineobj;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dbmessage;
        
        public PushLogRefrenceRequestBody() {
        }
        
        public PushLogRefrenceRequestBody(System.Collections.Generic.List<BioMetrixCore.LogPushService.LogDataBLL> devicedata, string DeviceIp, System.DateTime lastimportdate, BioMetrixCore.LogPushService.MachineBLL machineobj, string dbmessage) {
            this.devicedata = devicedata;
            this.DeviceIp = DeviceIp;
            this.lastimportdate = lastimportdate;
            this.machineobj = machineobj;
            this.dbmessage = dbmessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushLogRefrenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushLogRefrenceResponse", Namespace="http://tempuri.org/", Order=0)]
        public BioMetrixCore.LogPushService.PushLogRefrenceResponseBody Body;
        
        public PushLogRefrenceResponse() {
        }
        
        public PushLogRefrenceResponse(BioMetrixCore.LogPushService.PushLogRefrenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PushLogRefrenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PushLogRefrenceResult;
        
        public PushLogRefrenceResponseBody() {
        }
        
        public PushLogRefrenceResponseBody(string PushLogRefrenceResult) {
            this.PushLogRefrenceResult = PushLogRefrenceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMachineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMachine", Namespace="http://tempuri.org/", Order=0)]
        public BioMetrixCore.LogPushService.GetAllMachineRequestBody Body;
        
        public GetAllMachineRequest() {
        }
        
        public GetAllMachineRequest(BioMetrixCore.LogPushService.GetAllMachineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMachineRequestBody {
        
        public GetAllMachineRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMachineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMachineResponse", Namespace="http://tempuri.org/", Order=0)]
        public BioMetrixCore.LogPushService.GetAllMachineResponseBody Body;
        
        public GetAllMachineResponse() {
        }
        
        public GetAllMachineResponse(BioMetrixCore.LogPushService.GetAllMachineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMachineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BioMetrixCore.LogPushService.MachineBLL> GetAllMachineResult;
        
        public GetAllMachineResponseBody() {
        }
        
        public GetAllMachineResponseBody(System.Collections.Generic.List<BioMetrixCore.LogPushService.MachineBLL> GetAllMachineResult) {
            this.GetAllMachineResult = GetAllMachineResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogPushSoapChannel : BioMetrixCore.LogPushService.LogPushSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogPushSoapClient : System.ServiceModel.ClientBase<BioMetrixCore.LogPushService.LogPushSoap>, BioMetrixCore.LogPushService.LogPushSoap {
        
        public LogPushSoapClient() {
        }
        
        public LogPushSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogPushSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogPushSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogPushSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BioMetrixCore.LogPushService.PushLogRefrenceResponse BioMetrixCore.LogPushService.LogPushSoap.PushLogRefrence(BioMetrixCore.LogPushService.PushLogRefrenceRequest request) {
            return base.Channel.PushLogRefrence(request);
        }
        
        public string PushLogRefrence(System.Collections.Generic.List<BioMetrixCore.LogPushService.LogDataBLL> devicedata, string DeviceIp, System.DateTime lastimportdate, BioMetrixCore.LogPushService.MachineBLL machineobj, string dbmessage) {
            BioMetrixCore.LogPushService.PushLogRefrenceRequest inValue = new BioMetrixCore.LogPushService.PushLogRefrenceRequest();
            inValue.Body = new BioMetrixCore.LogPushService.PushLogRefrenceRequestBody();
            inValue.Body.devicedata = devicedata;
            inValue.Body.DeviceIp = DeviceIp;
            inValue.Body.lastimportdate = lastimportdate;
            inValue.Body.machineobj = machineobj;
            inValue.Body.dbmessage = dbmessage;
            BioMetrixCore.LogPushService.PushLogRefrenceResponse retVal = ((BioMetrixCore.LogPushService.LogPushSoap)(this)).PushLogRefrence(inValue);
            return retVal.Body.PushLogRefrenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BioMetrixCore.LogPushService.PushLogRefrenceResponse> BioMetrixCore.LogPushService.LogPushSoap.PushLogRefrenceAsync(BioMetrixCore.LogPushService.PushLogRefrenceRequest request) {
            return base.Channel.PushLogRefrenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<BioMetrixCore.LogPushService.PushLogRefrenceResponse> PushLogRefrenceAsync(System.Collections.Generic.List<BioMetrixCore.LogPushService.LogDataBLL> devicedata, string DeviceIp, System.DateTime lastimportdate, BioMetrixCore.LogPushService.MachineBLL machineobj, string dbmessage) {
            BioMetrixCore.LogPushService.PushLogRefrenceRequest inValue = new BioMetrixCore.LogPushService.PushLogRefrenceRequest();
            inValue.Body = new BioMetrixCore.LogPushService.PushLogRefrenceRequestBody();
            inValue.Body.devicedata = devicedata;
            inValue.Body.DeviceIp = DeviceIp;
            inValue.Body.lastimportdate = lastimportdate;
            inValue.Body.machineobj = machineobj;
            inValue.Body.dbmessage = dbmessage;
            return ((BioMetrixCore.LogPushService.LogPushSoap)(this)).PushLogRefrenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BioMetrixCore.LogPushService.GetAllMachineResponse BioMetrixCore.LogPushService.LogPushSoap.GetAllMachine(BioMetrixCore.LogPushService.GetAllMachineRequest request) {
            return base.Channel.GetAllMachine(request);
        }
        
        public System.Collections.Generic.List<BioMetrixCore.LogPushService.MachineBLL> GetAllMachine() {
            BioMetrixCore.LogPushService.GetAllMachineRequest inValue = new BioMetrixCore.LogPushService.GetAllMachineRequest();
            inValue.Body = new BioMetrixCore.LogPushService.GetAllMachineRequestBody();
            BioMetrixCore.LogPushService.GetAllMachineResponse retVal = ((BioMetrixCore.LogPushService.LogPushSoap)(this)).GetAllMachine(inValue);
            return retVal.Body.GetAllMachineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BioMetrixCore.LogPushService.GetAllMachineResponse> BioMetrixCore.LogPushService.LogPushSoap.GetAllMachineAsync(BioMetrixCore.LogPushService.GetAllMachineRequest request) {
            return base.Channel.GetAllMachineAsync(request);
        }
        
        public System.Threading.Tasks.Task<BioMetrixCore.LogPushService.GetAllMachineResponse> GetAllMachineAsync() {
            BioMetrixCore.LogPushService.GetAllMachineRequest inValue = new BioMetrixCore.LogPushService.GetAllMachineRequest();
            inValue.Body = new BioMetrixCore.LogPushService.GetAllMachineRequestBody();
            return ((BioMetrixCore.LogPushService.LogPushSoap)(this)).GetAllMachineAsync(inValue);
        }
    }
}
