//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAttendance.UpdateSoftwareInformation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdateSoftwareInformation.UpdateLoginServiceSoap")]
    public interface UpdateLoginServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSoftwareInformation", ReplyAction="*")]
        void UpdateSoftwareInformation(System.Nullable<int> port);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSoftwareInformation", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateSoftwareInformationAsync(System.Nullable<int> port);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpdateLoginServiceSoapChannel : eAttendance.UpdateSoftwareInformation.UpdateLoginServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateLoginServiceSoapClient : System.ServiceModel.ClientBase<eAttendance.UpdateSoftwareInformation.UpdateLoginServiceSoap>, eAttendance.UpdateSoftwareInformation.UpdateLoginServiceSoap {
        
        public UpdateLoginServiceSoapClient() {
        }
        
        public UpdateLoginServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateLoginServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateLoginServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateLoginServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateSoftwareInformation(System.Nullable<int> port) {
            base.Channel.UpdateSoftwareInformation(port);
        }
        
        public System.Threading.Tasks.Task UpdateSoftwareInformationAsync(System.Nullable<int> port) {
            return base.Channel.UpdateSoftwareInformationAsync(port);
        }
    }
}
